import { api } from './client';

// Lightweight lookup type for dropdowns
export interface VendorLookup {
  id: number;
  code: string;
  name: string;
}

// Full vendor type
export interface YarnVendor {
  id: number;
  code: string;
  name: string;
  contactPerson: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  city: string | null;
  creditLimit: string | null;
  paymentTerms: number;
  rating: number | null;
  notes: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface VendorFormData {
  code?: string; // Auto-generated by backend if not provided
  name: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  creditLimit?: number;
  paymentTerms?: number;
  rating?: number;
  notes?: string;
  isActive?: boolean;
}

export const yarnVendorsApi = {
  /**
   * Get lightweight lookup data for dropdowns
   */
  async getLookup(): Promise<VendorLookup[]> {
    const response = await api.get<{ data: VendorLookup[] }>('/yarn/vendors/lookup');
    return response.data.data;
  },

  /**
   * Get all vendors
   */
  async getAll(): Promise<YarnVendor[]> {
    const response = await api.get<{ data: YarnVendor[] }>('/yarn/vendors');
    return response.data.data;
  },

  /**
   * Get a single vendor by ID
   */
  async getById(id: number): Promise<YarnVendor> {
    const response = await api.get<{ data: YarnVendor }>(`/yarn/vendors/${id}`);
    return response.data.data;
  },

  /**
   * Create a new vendor
   */
  async create(data: VendorFormData): Promise<YarnVendor> {
    const response = await api.post<{ message: string; data: YarnVendor }>(
      '/yarn/vendors',
      data
    );
    return response.data.data;
  },

  /**
   * Update an existing vendor
   */
  async update(id: number, data: Partial<VendorFormData>): Promise<YarnVendor> {
    const response = await api.put<{ message: string; data: YarnVendor }>(
      `/yarn/vendors/${id}`,
      data
    );
    return response.data.data;
  },

  /**
   * Delete (deactivate) a vendor
   */
  async delete(id: number): Promise<void> {
    await api.delete(`/yarn/vendors/${id}`);
  },
};
