'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/atoms/Button';
import { Input } from '@/components/atoms/Input';
import { useToast } from '@/contexts/ToastContext';
import { yarnVendorsApi, VendorFormData } from '@/lib/api/yarn-vendors';

// Pakistani cities for dropdown
const PAKISTAN_CITIES = [
  'Faisalabad',
  'Karachi',
  'Lahore',
  'Multan',
  'Rawalpindi',
  'Islamabad',
  'Gujranwala',
  'Sialkot',
  'Peshawar',
  'Quetta',
  'Other',
];

// Payment terms options
const PAYMENT_TERMS_OPTIONS = [
  { value: 7, label: '7 Days' },
  { value: 15, label: '15 Days' },
  { value: 30, label: '30 Days' },
  { value: 45, label: '45 Days' },
  { value: 60, label: '60 Days' },
  { value: 90, label: '90 Days' },
];

// Form validation schema
const vendorSchema = z.object({
  code: z.string().optional(), // Auto-generated by backend
  name: z.string().min(2, 'Vendor name is required'),
  contactPerson: z.string().min(2, 'Contact person name is required'),
  phone: z.string().min(10, 'Valid phone number is required'),
  email: z.string().email('Invalid email address').optional().or(z.literal('')),
  address: z.string().optional(),
  city: z.string().optional(),
  country: z.string().optional(),
  creditLimit: z.coerce.number().min(0, 'Credit limit must be 0 or more'),
  paymentTerms: z.coerce.number().min(1, 'Payment terms required'),
  openingBalance: z.coerce.number().optional(),
  rating: z.coerce.number().min(1).max(5),
  isActive: z.boolean(),
  notes: z.string().optional(),
});

type VendorForm = z.infer<typeof vendorSchema>;

export default function NewVendorPage() {
  const router = useRouter();
  const { showToast } = useToast();
  const [isLoading, setIsLoading] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<VendorForm>({
    resolver: zodResolver(vendorSchema),
    defaultValues: {
      country: 'Pakistan',
      creditLimit: 100000,
      paymentTerms: 30,
      openingBalance: 0,
      rating: 3,
      isActive: true,
    },
  });

  const watchedRating = watch('rating');

  const onSubmit = async (data: VendorForm) => {
    setIsLoading(true);
    try {
      // Transform form data to API format
      const apiData: VendorFormData = {
        name: data.name,
        contactPerson: data.contactPerson || undefined,
        phone: data.phone || undefined,
        email: data.email || undefined,
        address: data.address || undefined,
        city: data.city || undefined,
        creditLimit: data.creditLimit,
        paymentTerms: data.paymentTerms,
        rating: data.rating,
        notes: data.notes || undefined,
        isActive: data.isActive,
      };

      await yarnVendorsApi.create(apiData);
      showToast('success', `Vendor "${data.name}" created successfully!`);
      router.push('/yarn/vendors');
    } catch (error: any) {
      const message = error.response?.data?.error || 'Failed to create vendor';
      showToast('error', message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-3xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 text-sm">
            <Link href="/yarn" className="text-neutral-400 hover:text-white">
              Yarn
            </Link>
            <span className="text-neutral-600">/</span>
            <Link href="/yarn/vendors" className="text-neutral-400 hover:text-white">
              Vendors
            </Link>
            <span className="text-neutral-600">/</span>
            <span className="text-white">New</span>
          </div>
          <h1 className="text-2xl font-semibold text-white mt-2">Add New Vendor</h1>
          <p className="text-neutral-400 mt-1">
            Register a new yarn supplier
          </p>
        </div>
        <Button variant="ghost" onClick={() => router.back()}>
          Cancel
        </Button>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Basic Information */}
        <div className="bg-factory-dark rounded-2xl border border-factory-border p-6">
          <h2 className="text-lg font-semibold text-white mb-4">
            Basic Information
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Vendor Code */}
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1.5">
                Vendor Code
              </label>
              <div className="px-4 py-2.5 rounded-xl bg-factory-gray border border-factory-border text-neutral-400 italic">
                Auto-generated (e.g., YV-0001)
              </div>
              <p className="text-xs text-neutral-500 mt-1">
                System will automatically assign a unique code
              </p>
            </div>

            {/* Vendor Name */}
            <Input
              label="Vendor Name *"
              placeholder="Enter vendor/company name"
              error={errors.name?.message}
              {...register('name')}
            />

            {/* Contact Person */}
            <Input
              label="Contact Person *"
              placeholder="Primary contact name"
              error={errors.contactPerson?.message}
              {...register('contactPerson')}
            />

            {/* Phone */}
            <Input
              label="Phone Number *"
              placeholder="0300-1234567"
              error={errors.phone?.message}
              {...register('phone')}
            />

            {/* Email */}
            <Input
              label="Email"
              type="email"
              placeholder="email@example.com"
              error={errors.email?.message}
              {...register('email')}
            />
          </div>
        </div>

        {/* Address */}
        <div className="bg-factory-dark rounded-2xl border border-factory-border p-6">
          <h2 className="text-lg font-semibold text-white mb-4">
            Address
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Address Line */}
            <div className="md:col-span-2">
              <Input
                label="Address"
                placeholder="Street address, building, area"
                error={errors.address?.message}
                {...register('address')}
              />
            </div>

            {/* City */}
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1.5">
                City
              </label>
              <select
                {...register('city')}
                className="w-full px-4 py-2.5 rounded-xl bg-factory-gray border border-factory-border text-white focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                <option value="">Select City</option>
                {PAKISTAN_CITIES.map((city) => (
                  <option key={city} value={city}>
                    {city}
                  </option>
                ))}
              </select>
            </div>

            {/* Country */}
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1.5">
                Country
              </label>
              <select
                {...register('country')}
                className="w-full px-4 py-2.5 rounded-xl bg-factory-gray border border-factory-border text-white focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                <option value="Pakistan">Pakistan</option>
                <option value="China">China</option>
                <option value="India">India</option>
                <option value="Bangladesh">Bangladesh</option>
                <option value="Turkey">Turkey</option>
                <option value="Other">Other</option>
              </select>
            </div>
          </div>
        </div>

        {/* Financial Terms */}
        <div className="bg-factory-dark rounded-2xl border border-factory-border p-6">
          <h2 className="text-lg font-semibold text-white mb-4">
            Financial Terms
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Credit Limit */}
            <div>
              <Input
                label="Credit Limit (PKR) *"
                type="number"
                placeholder="100000"
                error={errors.creditLimit?.message}
                {...register('creditLimit')}
              />
              <p className="text-xs text-neutral-500 mt-1">
                Maximum outstanding balance allowed
              </p>
            </div>

            {/* Payment Terms */}
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-1.5">
                Payment Terms *
              </label>
              <select
                {...register('paymentTerms')}
                className="w-full px-4 py-2.5 rounded-xl bg-factory-gray border border-factory-border text-white focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                {PAYMENT_TERMS_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
              <p className="text-xs text-neutral-500 mt-1">
                Days to pay after purchase
              </p>
            </div>

            {/* Opening Balance */}
            <div>
              <Input
                label="Opening Balance (PKR)"
                type="number"
                placeholder="0"
                error={errors.openingBalance?.message}
                {...register('openingBalance')}
              />
              <p className="text-xs text-neutral-500 mt-1">
                Existing balance if any
              </p>
            </div>
          </div>
        </div>

        {/* Rating & Status */}
        <div className="bg-factory-dark rounded-2xl border border-factory-border p-6">
          <h2 className="text-lg font-semibold text-white mb-4">
            Rating & Status
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Rating */}
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-3">
                Vendor Rating
              </label>
              <div className="flex gap-2">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    type="button"
                    onClick={() => setValue('rating', star)}
                    className={`text-3xl transition-colors ${
                      star <= watchedRating
                        ? 'text-yellow-400 hover:text-yellow-300'
                        : 'text-neutral-600 hover:text-neutral-500'
                    }`}
                  >
                    ★
                  </button>
                ))}
              </div>
              <p className="text-xs text-neutral-500 mt-2">
                Rate vendor quality and reliability
              </p>
            </div>

            {/* Status */}
            <div>
              <label className="block text-sm font-medium text-neutral-300 mb-3">
                Status
              </label>
              <div className="flex items-center justify-between p-4 bg-factory-gray rounded-xl">
                <div>
                  <p className="text-white font-medium">Active Vendor</p>
                  <p className="text-sm text-neutral-400">
                    Active vendors appear in dropdowns
                  </p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    {...register('isActive')}
                    className="sr-only peer"
                  />
                  <div className="w-11 h-6 bg-factory-border rounded-full peer peer-checked:bg-primary-500 peer-focus:ring-2 peer-focus:ring-primary-500/50 after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full" />
                </label>
              </div>
            </div>
          </div>
        </div>

        {/* Notes */}
        <div className="bg-factory-dark rounded-2xl border border-factory-border p-6">
          <label className="block text-sm font-medium text-neutral-300 mb-1.5">
            Notes (Optional)
          </label>
          <textarea
            {...register('notes')}
            rows={3}
            className="w-full px-4 py-2.5 rounded-xl bg-factory-gray border border-factory-border text-white placeholder-neutral-500 focus:outline-none focus:ring-2 focus:ring-primary-500"
            placeholder="Any additional notes about this vendor..."
          />
        </div>

        {/* Submit */}
        <div className="flex justify-end gap-3">
          <Button type="button" variant="secondary" onClick={() => router.back()}>
            Cancel
          </Button>
          <Button type="submit" disabled={isLoading}>
            {isLoading ? 'Creating...' : 'Create Vendor'}
          </Button>
        </div>
      </form>
    </div>
  );
}
