/**
 * General Supplier Types
 *
 * Types for managing general suppliers (non-yarn, non-dyeing vendors):
 * - Needles, materials, services, etc.
 * - Financial ledger (payments, balances)
 * - Material receipts and returns
 */

// ============================================
// VENDOR TYPE ENUM
// ============================================

export type VendorTypeEnum = 'YARN' | 'DYEING' | 'GENERAL';

export const VENDOR_TYPES: Record<VendorTypeEnum, {
  code: VendorTypeEnum;
  label: string;
  description: string;
}> = {
  YARN: {
    code: 'YARN',
    label: 'Yarn Vendor',
    description: 'Suppliers of yarn and thread materials',
  },
  DYEING: {
    code: 'DYEING',
    label: 'Dyeing Vendor',
    description: 'Dyeing and finishing service providers',
  },
  GENERAL: {
    code: 'GENERAL',
    label: 'General Supplier',
    description: 'Suppliers of needles, parts, materials, and services',
  },
};

// ============================================
// SUPPLIER TYPE ENUM
// ============================================

export type SupplierType = 'MATERIALS' | 'PARTS' | 'SERVICES' | 'TRANSPORT' | 'OTHER';

export const SUPPLIER_TYPES: Record<SupplierType, {
  code: SupplierType;
  label: string;
  description: string;
}> = {
  MATERIALS: {
    code: 'MATERIALS',
    label: 'Materials',
    description: 'Needles, oils, packaging materials, etc.',
  },
  PARTS: {
    code: 'PARTS',
    label: 'Spare Parts',
    description: 'Machine parts and components',
  },
  SERVICES: {
    code: 'SERVICES',
    label: 'Services',
    description: 'Maintenance, repair, and other services',
  },
  TRANSPORT: {
    code: 'TRANSPORT',
    label: 'Transport',
    description: 'Logistics and shipping providers',
  },
  OTHER: {
    code: 'OTHER',
    label: 'Other',
    description: 'Other general suppliers',
  },
};

// ============================================
// GENERAL SUPPLIER ENTITY
// ============================================

export interface GeneralSupplier {
  id: string;
  code: string;                    // Unique: SUP-001
  name: string;
  supplierType: SupplierType;
  contactPerson: string;
  phone: string;
  email?: string;
  address?: string;
  city?: string;

  // Tax information
  ntn?: string;                    // National Tax Number
  strn?: string;                   // Sales Tax Registration Number

  // Financial
  creditLimit: number;             // Maximum credit allowed (PKR)
  paymentTerms: number;            // Payment terms in days
  currentBalance: number;          // Current amount owed to supplier

  // Bank details
  bankDetails?: {
    bankName?: string;
    accountTitle?: string;
    accountNumber?: string;
    branchCode?: string;
    iban?: string;
  };

  // Status & Rating
  rating: number;                  // 1-5 stars
  isActive: boolean;
  notes?: string;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

export interface GeneralSupplierFormData {
  code?: string; // Auto-generated by backend
  name: string;
  supplierType: SupplierType;
  contactPerson?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  ntn?: string;
  strn?: string;
  creditLimit: number;
  paymentTerms: number;
  openingBalance?: number;
  bankDetails?: {
    bankName?: string;
    accountTitle?: string;
    accountNumber?: string;
    branchCode?: string;
    iban?: string;
  };
  rating: number;
  isActive: boolean;
  notes?: string;
}

// ============================================
// VENDOR LEDGER ENTRY TYPES
// ============================================

export type VendorLedgerType =
  | 'OPENING_BALANCE'      // Initial balance when vendor added
  | 'PURCHASE'             // Goods/services received (debit - we owe more)
  | 'PAYMENT_MADE'         // Payment made (credit - we owe less)
  | 'RETURN'               // Goods returned (credit - reduces what we owe)
  | 'ADJUSTMENT'           // Manual adjustment (can be debit or credit)
  | 'DEBIT_NOTE'           // Debit note issued
  | 'CREDIT_NOTE';         // Credit note received

export const VENDOR_LEDGER_TYPES: Record<VendorLedgerType, {
  code: VendorLedgerType;
  label: string;
  description: string;
  isDebit: boolean | 'both';
}> = {
  OPENING_BALANCE: {
    code: 'OPENING_BALANCE',
    label: 'Opening Balance',
    description: 'Initial balance when vendor was added',
    isDebit: 'both',
  },
  PURCHASE: {
    code: 'PURCHASE',
    label: 'Purchase',
    description: 'Goods/services received from vendor',
    isDebit: true,
  },
  PAYMENT_MADE: {
    code: 'PAYMENT_MADE',
    label: 'Payment Made',
    description: 'Payment made to vendor',
    isDebit: false,
  },
  RETURN: {
    code: 'RETURN',
    label: 'Return',
    description: 'Goods returned to vendor',
    isDebit: false,
  },
  ADJUSTMENT: {
    code: 'ADJUSTMENT',
    label: 'Adjustment',
    description: 'Manual balance adjustment',
    isDebit: 'both',
  },
  DEBIT_NOTE: {
    code: 'DEBIT_NOTE',
    label: 'Debit Note',
    description: 'Debit note issued to vendor',
    isDebit: true,
  },
  CREDIT_NOTE: {
    code: 'CREDIT_NOTE',
    label: 'Credit Note',
    description: 'Credit note received from vendor',
    isDebit: false,
  },
};

export interface VendorLedgerEntry {
  id: string;
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;
  entryDate: string;
  entryType: VendorLedgerType;

  // Amounts (all in PKR)
  debit: number;                   // Increases balance (we owe more)
  credit: number;                  // Decreases balance (we owe less)
  balance: number;                 // Running balance after this entry

  // Reference to source document
  referenceType?: string;
  referenceId?: string;
  referenceNumber?: string;        // Invoice/challan/voucher number

  description: string;
  createdBy?: string;
  createdAt: string;
}

// ============================================
// MATERIAL RECEIPT
// ============================================

export type MaterialReceiptType = 'PURCHASE' | 'RETURN_IN' | 'ADJUSTMENT';

export const MATERIAL_RECEIPT_TYPES: Record<MaterialReceiptType, {
  code: MaterialReceiptType;
  label: string;
  description: string;
}> = {
  PURCHASE: {
    code: 'PURCHASE',
    label: 'Purchase',
    description: 'Normal purchase receipt',
  },
  RETURN_IN: {
    code: 'RETURN_IN',
    label: 'Return In',
    description: 'Goods returned by customer',
  },
  ADJUSTMENT: {
    code: 'ADJUSTMENT',
    label: 'Adjustment',
    description: 'Inventory adjustment',
  },
};

export type QualityStatus = 'PENDING_INSPECTION' | 'APPROVED' | 'REJECTED' | 'PARTIAL';

export const QUALITY_STATUSES: Record<QualityStatus, {
  code: QualityStatus;
  label: string;
  color: string;
}> = {
  PENDING_INSPECTION: {
    code: 'PENDING_INSPECTION',
    label: 'Pending',
    color: 'warning',
  },
  APPROVED: {
    code: 'APPROVED',
    label: 'Approved',
    color: 'success',
  },
  REJECTED: {
    code: 'REJECTED',
    label: 'Rejected',
    color: 'error',
  },
  PARTIAL: {
    code: 'PARTIAL',
    label: 'Partial Accept',
    color: 'warning',
  },
};

export type MaterialIssueType =
  | 'WRONG_TYPE'
  | 'QUALITY_DEFECT'
  | 'SHORT_WEIGHT'
  | 'DAMAGED'
  | 'COLOR_MISMATCH'
  | 'OTHER';

export const MATERIAL_ISSUE_TYPES: Record<MaterialIssueType, {
  code: MaterialIssueType;
  label: string;
  description: string;
}> = {
  WRONG_TYPE: {
    code: 'WRONG_TYPE',
    label: 'Wrong Type',
    description: 'Different item than ordered',
  },
  QUALITY_DEFECT: {
    code: 'QUALITY_DEFECT',
    label: 'Quality Defect',
    description: 'Does not meet quality standards',
  },
  SHORT_WEIGHT: {
    code: 'SHORT_WEIGHT',
    label: 'Short Weight/Quantity',
    description: 'Actual quantity less than invoiced',
  },
  DAMAGED: {
    code: 'DAMAGED',
    label: 'Damaged',
    description: 'Items damaged during transport',
  },
  COLOR_MISMATCH: {
    code: 'COLOR_MISMATCH',
    label: 'Color Mismatch',
    description: 'Color does not match specification',
  },
  OTHER: {
    code: 'OTHER',
    label: 'Other',
    description: 'Other issue',
  },
};

export interface MaterialReceiptItem {
  id: string;
  description: string;
  quantity: number;
  unit: string;
  ratePerUnit: number;
  amount: number;
  notes?: string;
}

export interface MaterialReceipt {
  id: string;
  receiptNumber: string;           // GRN-2024-001
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;

  // Vendor display info
  vendorName?: string;
  vendorCode?: string;

  receiptDate: string;
  receiptType: MaterialReceiptType;
  invoiceNumber?: string;
  gatePassNumber?: string;
  vehicleNumber?: string;

  // Quantity summary
  orderedQty?: number;
  receivedQty: number;
  acceptedQty: number;
  rejectedQty: number;
  unit: string;

  // Financial
  ratePerUnit?: number;
  grossAmount: number;
  discountAmount: number;
  taxAmount: number;
  netAmount: number;

  // Quality
  qualityStatus: QualityStatus;
  qualityCheckedBy?: string;
  qualityCheckedAt?: string;
  qualityNotes?: string;

  // Issue tracking
  hasIssue: boolean;
  issueType?: MaterialIssueType;
  issueDescription?: string;

  // Items
  items?: MaterialReceiptItem[];

  // Ledger link
  ledgerEntryId?: string;

  createdBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MaterialReceiptFormData {
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;
  receiptDate: string;
  receiptType: MaterialReceiptType;
  invoiceNumber?: string;
  gatePassNumber?: string;
  vehicleNumber?: string;
  items: {
    description: string;
    quantity: number;
    unit: string;
    ratePerUnit: number;
  }[];
  discountAmount?: number;
  taxAmount?: number;
  notes?: string;
}

// ============================================
// MATERIAL RETURN
// ============================================

export type ReplacementStatus =
  | 'REPORTED'              // Issue reported, pending action
  | 'RETURN_PENDING'        // Approved for return, not yet returned
  | 'RETURNED'              // Material has been returned to vendor
  | 'REPLACEMENT_PENDING'   // Waiting for replacement
  | 'REPLACED'              // Replacement received
  | 'CREDITED'              // Vendor gave credit instead of replacement
  | 'CLOSED';               // Issue resolved and closed

export const REPLACEMENT_STATUSES: Record<ReplacementStatus, {
  code: ReplacementStatus;
  label: string;
  color: string;
  isOpen: boolean;
}> = {
  REPORTED: {
    code: 'REPORTED',
    label: 'Reported',
    color: 'warning',
    isOpen: true,
  },
  RETURN_PENDING: {
    code: 'RETURN_PENDING',
    label: 'Return Pending',
    color: 'warning',
    isOpen: true,
  },
  RETURNED: {
    code: 'RETURNED',
    label: 'Returned',
    color: 'info',
    isOpen: true,
  },
  REPLACEMENT_PENDING: {
    code: 'REPLACEMENT_PENDING',
    label: 'Replacement Pending',
    color: 'warning',
    isOpen: true,
  },
  REPLACED: {
    code: 'REPLACED',
    label: 'Replaced',
    color: 'success',
    isOpen: false,
  },
  CREDITED: {
    code: 'CREDITED',
    label: 'Credited',
    color: 'success',
    isOpen: false,
  },
  CLOSED: {
    code: 'CLOSED',
    label: 'Closed',
    color: 'neutral',
    isOpen: false,
  },
};

export interface MaterialReturn {
  id: string;
  returnNumber: string;            // RET-2024-001
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;
  materialReceiptId?: string;

  // Vendor display info
  vendorName?: string;
  vendorCode?: string;

  returnDate: string;
  returnChallanNumber?: string;

  // Issue details
  issueType: MaterialIssueType;
  issueDescription: string;

  // Return quantity
  returnedQuantity: number;
  unit: string;
  returnValue: number;

  // Resolution
  replacementStatus: ReplacementStatus;
  replacementQuantity?: number;
  replacementDate?: string;
  replacementReceiptId?: string;
  creditAmount?: number;
  creditDate?: string;
  creditNoteNumber?: string;

  resolvedAt?: string;
  resolvedBy?: string;
  resolutionNotes?: string;

  // Ledger links
  debitLedgerEntryId?: string;
  creditLedgerEntryId?: string;

  createdBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MaterialReturnFormData {
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;
  materialReceiptId?: string;
  returnDate: string;
  returnChallanNumber?: string;
  issueType: MaterialIssueType;
  issueDescription: string;
  returnedQuantity: number;
  unit: string;
  returnValue: number;
  notes?: string;
}

// ============================================
// VENDOR PAYMENT
// ============================================

export type PaymentMethod = 'CASH' | 'CHEQUE' | 'BANK_TRANSFER' | 'ONLINE';

export const PAYMENT_METHODS: Record<PaymentMethod, {
  code: PaymentMethod;
  label: string;
  requiresReference: boolean;
  requiresBank: boolean;
}> = {
  CASH: {
    code: 'CASH',
    label: 'Cash',
    requiresReference: false,
    requiresBank: false,
  },
  CHEQUE: {
    code: 'CHEQUE',
    label: 'Cheque',
    requiresReference: true,
    requiresBank: true,
  },
  BANK_TRANSFER: {
    code: 'BANK_TRANSFER',
    label: 'Bank Transfer',
    requiresReference: true,
    requiresBank: true,
  },
  ONLINE: {
    code: 'ONLINE',
    label: 'Online Payment',
    requiresReference: true,
    requiresBank: false,
  },
};

export interface VendorPayment {
  id: string;
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;

  // Vendor display info
  vendorName?: string;
  vendorCode?: string;

  paymentDate: string;
  amount: number;
  paymentMethod: PaymentMethod;
  referenceNumber?: string;        // Cheque # or transaction ID
  transactionRef?: string;         // Bank transaction reference
  bankName?: string;
  notes?: string;
  voucherNumber: string;           // Auto-generated: PAY-2024-001

  // Cheque link
  chequeId?: string;

  // Ledger link
  ledgerEntryId?: string;

  createdBy?: string;
  createdAt: string;
}

export interface VendorPaymentFormData {
  vendorType: VendorTypeEnum;
  yarnVendorId?: string;
  dyeingVendorId?: string;
  generalSupplierId?: string;
  paymentDate: string;
  amount: number;
  paymentMethod: PaymentMethod;
  referenceNumber?: string;
  bankName?: string;
  notes?: string;
  // Cheque details (if payment method is CHEQUE)
  chequeNumber?: string;
  chequeDate?: string;
}

// ============================================
// AGING & SUMMARY
// ============================================

export interface AgingBucket {
  current: number;      // Not yet due
  days1To30: number;    // 1-30 days overdue
  days31To60: number;   // 31-60 days overdue
  days61To90: number;   // 61-90 days overdue
  daysOver90: number;   // Over 90 days overdue
  total: number;
}

export interface VendorAgingEntry {
  vendorType: VendorTypeEnum;
  vendorId: string;
  vendorCode: string;
  vendorName: string;
  creditLimit: number;
  aging: AgingBucket;
}

export interface PayablesAgingReport {
  asOfDate: string;
  summary: AgingBucket;
  byVendorType: {
    [key in VendorTypeEnum]?: AgingBucket;
  };
  entries: VendorAgingEntry[];
}

export interface SupplierSummary {
  totalPurchases: number;          // Total amount purchased (PKR)
  totalPayments: number;           // Total amount paid (PKR)
  currentBalance: number;          // Outstanding balance (PKR)
  totalMaterialReceived: number;   // Total quantity received
  returnCount: number;             // Total return issues
  pendingReturns: number;          // Open/unresolved issues
  lastPurchaseDate?: string;
  lastPaymentDate?: string;
}

export interface SupplierListFilters {
  search?: string;
  supplierType?: SupplierType | 'all';
  status?: 'all' | 'active' | 'inactive';
  hasBalance?: boolean;
  hasPendingIssues?: boolean;
  city?: string;
}

export interface PayablesSummary {
  totalPayables: number;
  overdueAmount: number;
  dueThisWeek: number;
  dueThisMonth: number;
  pendingCheques: number;
  pendingChequeAmount: number;
  byVendorType: {
    [key in VendorTypeEnum]?: {
      count: number;
      balance: number;
    };
  };
}

// ============================================
// UTILITY FUNCTIONS
// ============================================

/**
 * Generate a suggested supplier code from name
 */
export function suggestSupplierCode(name: string, existingCodes: string[]): string {
  // Get first 3 letters of name, uppercase
  const prefix = name.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase() || 'SUP';

  // Find the next available number
  let number = 1;
  let code = `${prefix}-${String(number).padStart(3, '0')}`;

  while (existingCodes.includes(code)) {
    number++;
    code = `${prefix}-${String(number).padStart(3, '0')}`;
  }

  return code;
}

/**
 * Calculate running balance for ledger entries
 */
export function calculateRunningBalance(
  entries: Omit<VendorLedgerEntry, 'balance'>[],
  openingBalance: number = 0
): VendorLedgerEntry[] {
  let runningBalance = openingBalance;

  return entries.map((entry) => {
    runningBalance = runningBalance + entry.debit - entry.credit;
    return {
      ...entry,
      balance: runningBalance,
    };
  });
}

/**
 * Format currency for display
 */
export function formatPKR(amount: number): string {
  return new Intl.NumberFormat('en-PK', {
    style: 'currency',
    currency: 'PKR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

/**
 * Format date for display
 */
export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-PK', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

/**
 * Get vendor display name based on type
 */
export function getVendorTypeLabel(type: VendorTypeEnum): string {
  return VENDOR_TYPES[type]?.label || type;
}
